import { FeedPost } from '@/components/feed/PostCard';

export const FEED_POSTS: FeedPost[] = [
  {
    id: '1',
    authorName: 'Eli',
    authorInitial: 'E',
    authorColor: ['#FF5A36', '#6B5CE0'],
    action: 'planned a day',
    location: 'Silver Lake',
    timeAgo: '2h ago',
    title: 'Silver Lake food crawl',
    driveTime: '1h 10m',
    budget: '$61',
    gas: '$7',
    miles: '28mi',
    tags: ['food crawl', 'cheap eats'],
    likes: 214,
    comments: 33,
    saves: 90,
    route: [
      { x: 20, y: 70 },
      { x: 38, y: 55 },
      { x: 55, y: 60 },
      { x: 70, y: 38 },
      { x: 84, y: 30 },
    ],
  },
  {
    id: '2',
    authorName: 'Sofia',
    authorInitial: 'S',
    authorColor: ['#5AC8C0', '#2E7DA8'],
    action: 'posted a day',
    location: 'Downtown LA',
    timeAgo: 'yesterday',
    title: 'Museum day downtown',
    driveTime: '45m',
    budget: '$48',
    gas: '$5',
    miles: '19mi',
    tags: ['museum day', 'rainy day'],
    likes: 88,
    comments: 9,
    saves: 41,
    route: [
      { x: 25, y: 40 },
      { x: 45, y: 55 },
      { x: 60, y: 45 },
      { x: 78, y: 60 },
    ],
  },
  {
    id: '3',
    authorName: 'Marcus',
    authorInitial: 'M',
    authorColor: ['#9BE15D', '#3FA34D'],
    action: 'planned a day',
    location: 'Malibu',
    timeAgo: '3d ago',
    title: 'PCH beach day',
    driveTime: '2h 30m',
    budget: '$54',
    gas: '$22',
    miles: '96mi',
    tags: ['beach day', 'road trip'],
    likes: 351,
    comments: 47,
    saves: 120,
    route: [
      { x: 14, y: 30 },
      { x: 32, y: 44 },
      { x: 50, y: 54 },
      { x: 68, y: 62 },
      { x: 84, y: 70 },
    ],
  },
];